# =============================================================================
# Configuration for the Wikimedia Trends Engine Producer
# =============================================================================

wikimedia:
  stream_url: "https://stream.wikimedia.org/v2/stream/recentchange"

kafka:
  topic_name: "wikimedia.recentchange"

  # Performance and durability settings for the Kafka producer.
  producer_config:
    linger_ms: 5
    batch_size: 65536
    acks: "all"

aws:
  region: "eu-central-1"